# Generated by Django 5.2.8 on 2025-11-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_state_command_alter_location_lat_alter_location_lon"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="credits_img",
            field=models.CharField(
                blank=True,
                help_text="Image added to end. Store in show_dir/assets/credits directory.",
                max_length=30,
                null=True,
            ),
        ),
    ]
